
CREATE TABLE patients (
    "Id" VARCHAR(255) PRIMARY KEY,
    "BIRTHDATE" DATE,
    "DEATHDATE" DATE,
    "SSN" VARCHAR(255),
    "DRIVERS" VARCHAR(255),
    "PASSPORT" VARCHAR(255),
    "PREFIX" VARCHAR(255),
    "FIRST" VARCHAR(255),
    "LAST" VARCHAR(255),
    "SUFFIX" VARCHAR(255),
    "MAIDEN" VARCHAR(255),
    "MARITAL" VARCHAR(255),
    "RACE" VARCHAR(255),
    "ETHNICITY" VARCHAR(255),
    "GENDER" VARCHAR(255),
    "BIRTHPLACE" VARCHAR(255),
    "ADDRESS" VARCHAR(255),
    "CITY" VARCHAR(255),
    "STATE" VARCHAR(255),
    "COUNTY" VARCHAR(255),
    "FIPS" INTEGER,
    "ZIP" VARCHAR(255),
    "LAT" REAL,
    "LON" REAL,
    "HEALTHCARE_EXPENSES" REAL,
    "HEALTHCARE_COVERAGE" REAL,
    "INCOME" INTEGER
);

CREATE TABLE conditions (
    "START" DATE,
    "STOP" DATE,
    "PATIENT" VARCHAR(255),
    "ENCOUNTER" VARCHAR(255),
    "CODE" VARCHAR(255),
    "DESCRIPTION" VARCHAR(255)
);

CREATE TABLE encounters (
    "Id" VARCHAR(255) PRIMARY KEY,
    "START" TIMESTAMP,
    "STOP" TIMESTAMP,
    "PATIENT" VARCHAR(255),
    "ORGANIZATION" VARCHAR(255),
    "PROVIDER" VARCHAR(255),
    "PAYER" VARCHAR(255),
    "ENCOUNTERCLASS" VARCHAR(255),
    "CODE" VARCHAR(255),
    "DESCRIPTION" VARCHAR(255),
    "COST" REAL,
    "REASONCODE" VARCHAR(255),
    "REASONDESCRIPTION" VARCHAR(255)
);

CREATE TABLE medications (
    "START" TIMESTAMP,
    "STOP" TIMESTAMP,
    "PATIENT" VARCHAR(255),
    "PAYER" VARCHAR(255),
    "ENCOUNTER" VARCHAR(255),
    "CODE" VARCHAR(255),
    "DESCRIPTION" VARCHAR(255),
    "BASE_COST" REAL,
    "PAYER_COVERAGE" REAL,
    "DISPENSES" INTEGER,
    "TOTALCOST" REAL,
    "REASONCODE" VARCHAR(255),
    "REASONDESCRIPTION" VARCHAR(255)
);

CREATE TABLE organizations (
    "Id" VARCHAR(255) PRIMARY KEY,
    "NAME" VARCHAR(255),
    "ADDRESS" VARCHAR(255),
    "CITY" VARCHAR(255),
    "STATE" VARCHAR(255),
    "ZIP" VARCHAR(255),
    "LAT" REAL,
    "LON" REAL,
    "PHONE" VARCHAR(255),
    "REVENUE" REAL,
    "UTILIZATION" INTEGER
);

CREATE TABLE audit_logs (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    user_query TEXT NOT NULL,
    policy_verdict VARCHAR(50),
    rewritten_query TEXT,
    executed_sql TEXT,
    response TEXT,
    trace_id VARCHAR(255)
);
